services:
  - type: web
    name: yt-shorts-ai-producer
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: CF_ACCOUNT_ID
        sync: false
      - key: CF_API_TOKEN
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
    healthCheckPath: /
